import { Page } from '../core/pages';

export const page: Page[] = [
	{ id: 1001, name: 'Homepage', title: 'Homepage', slug: '/', component: 'HomeComponent' },
	{ id: 2001, name: 'Search', title: 'Search', slug: '/search', component: 'SearchComponent' },
	{ id: 2001, name: 'Profile', title: 'Profile', slug: '/profile', component: 'ProfileComponent' },
	{ id: 2101, name: 'Sign', title: 'Sign', slug: '/accedi', component: 'SignComponent' },
	{ id: 2201, name: 'Sign Up', title: 'Sign Up', slug: '/registrati', component: 'SignUpComponent' },
	{ id: 2301, name: 'Sign In', title: 'Sign In', slug: '/login', component: 'SignInComponent' },
	{ id: 2401, name: 'Retrieve Password', title: 'Retrieve Password', slug: '/recupera-password', component: 'SignForgottenComponent' },
	{ id: 3001, name: 'Regions', title: 'Regions', slug: '/regions', component: 'RegionsComponent' },
	{ id: 4001, name: 'Abruzzo', title: 'Region Abruzzo', slug: '/abruzzo', component: 'RegionDetailComponent' },
	{ id: 4002, name: 'Basilicata', title: 'Region Basilicata', slug: '/basilicata', component: 'RegionDetailComponent' },
	{ id: 4003, name: 'Calabria', title: 'Region Calabria', slug: '/calabria', component: 'RegionDetailComponent' },
	{ id: 4004, name: 'Campania', title: 'Region Campania', slug: '/campania', component: 'RegionDetailComponent' },
	{ id: 4005, name: 'Emilia-Romagna', title: 'Region Emilia-Romagna', slug: '/emilia-romagna', component: 'RegionDetailComponent' },
	{ id: 4006, name: 'Friuli-Venezia Giulia', title: 'Region Friuli-Venezia Giulia', slug: '/friuli-venezia-giulia', component: 'RegionDetailComponent' },
	{ id: 4007, name: 'Lazio', title: 'Region Lazio', slug: '/lazio', component: 'RegionDetailComponent' },
	{ id: 4008, name: 'Liguria', title: 'Region Liguria', slug: '/liguria', component: 'RegionDetailComponent' },
	{ id: 4009, name: 'Lombardia', title: 'Region Lombardia', slug: '/lombardia', component: 'RegionDetailComponent' },
	{ id: 4010, name: 'Marche', title: 'Region Marche', slug: '/marche', component: 'RegionDetailComponent' },
	{ id: 4011, name: 'Molise', title: 'Region Molise', slug: '/molise', component: 'RegionDetailComponent' },
	{ id: 4012, name: 'Piemonte', title: 'Region Piemonte', slug: '/piemonte', component: 'RegionDetailComponent' },
	{ id: 4013, name: 'Puglia', title: 'Region Puglia', slug: '/puglia', component: 'RegionDetailComponent' },
	{ id: 4014, name: 'Sardegna', title: 'Region Sardegna', slug: '/sardegna', component: 'RegionDetailComponent' },
	{ id: 4015, name: 'Sicilia', title: 'Region Sicilia', slug: '/sicilia', component: 'RegionDetailComponent' },
	{ id: 4016, name: 'Toscana', title: 'Region Toscana', slug: '/toscana', component: 'RegionDetailComponent' },
	{ id: 4017, name: 'Trentino-Alto Adige', title: 'Region Trentino-Alto Adige', slug: '/trentino-alto-adige', component: 'RegionDetailComponent' },
	{ id: 4018, name: 'Umbria', title: 'Region Umbria', slug: '/umbria', component: 'RegionDetailComponent' },
	{ id: 4019, name: 'Valle d\'Aosta', title: 'Region Valle d\'Aosta', slug: '/valle-d-aosta', component: 'RegionDetailComponent' },
	{ id: 4020, name: 'Veneto', title: 'Region Veneto', slug: '/veneto', component: 'RegionDetailComponent' },
];
